// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snoiffgiiphibkyngcyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub2lmZmdpaXBoaWJreW5nY3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODQxODUsImV4cCI6MjA3MTQ2MDE4NX0.ieyUAw8q5TWhvFgQiFbHWi6xjoGjspS6dU7uSIrx4k8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});